name: CI

on:
  # Triggers the workflow on push request event
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests in docker-compose
        run: docker-compose up --force-recreate --exit-code-from workspace
